//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastConnect.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IFastService")]
    public interface IFastService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastService/GetPrintFile", ReplyAction="http://tempuri.org/IFastService/GetPrintFileResponse")]
        System.IO.Stream GetPrintFile(System.Xml.Linq.XElement xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastService/GetPrintFile", ReplyAction="http://tempuri.org/IFastService/GetPrintFileResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetPrintFileAsync(System.Xml.Linq.XElement xml);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFastServiceChannel : FastConnect.ServiceReference1.IFastService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FastServiceClient : System.ServiceModel.ClientBase<FastConnect.ServiceReference1.IFastService>, FastConnect.ServiceReference1.IFastService {
        
        public FastServiceClient() {
        }
        
        public FastServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FastServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FastServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FastServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.IO.Stream GetPrintFile(System.Xml.Linq.XElement xml) {
            return base.Channel.GetPrintFile(xml);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetPrintFileAsync(System.Xml.Linq.XElement xml) {
            return base.Channel.GetPrintFileAsync(xml);
        }
    }
}
